
[terminal.shell]
program = "/bin/zsh"
args = ["-1"]

[window]
dimensions = { columns = 120, lines = 30 }
decorations = "Full"
opacity = 0.95

[scrolling]
history = 100000

[font]
normal = { family = "Cascadia Code NF", style = "Regular" }
italic = { family = "Cascadia Code NF", style = "Regular" }
bold_italic = { family = "Cascadia Code NF", style = "Regular" }
size = 12.0

[selection]
save_to_clipboard = true

[cursor]
style = "Block"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control" }

[general]
import = ["~/.config/alacritty/themes/themes/pastel_dark.toml"]

[terminal]


